apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-rollouts-1
  namespace: argocd
spec:
  project: test

  source:
    repoURL: https://github.com/MTuradek/argo-demo
    targetRevision: HEAD
    path: helm-guestbook-rollouts
  destination:
    server: https://kubernetes.docker.internal:6443
    namespace: guestbook

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
#      pull every 3 minutes from repository
      selfHeal: true
      prune: true
